---
- name: 'clone dotfiles'
  git:
    repo: "{{dotfiles_git}}"
    dest: "{{lookup('env', 'HOME')}}/dotfiles"
    clone: yes

- name: 'Copy dotfiles'
  copy:
    remote_src: true
    src: "{{lookup('env', 'HOME')}}/dotfiles/{{item}}"
    dest: "{{lookup('env', 'HOME')}}/{{item}}"
  loop:
    - .bashrc
    - .gitconfig
    - .gitconfig-user
    - .gitignore-global
    - .vimrc
    - .Xresources
    - .config
    - .xinitrc
