suckless_build_root: '/home/void/suckless'
suckless_software:
  - name: 'slstatus'
    version: '1.0'
    url: "https://dl.suckless.org/tools"

  - name: dmenu
    version: '5.3'
    url: "https://dl.suckless.org/tools"

  - name: st
    version: '0.9.2'
    url: "https://dl.suckless.org/st"

  - name: dwm
    version: '6.5'
    url: "https://dl.suckless.org/dwm"
