---
- name: 'Remove outdated libs'
  file:
    path: '/opt/resolve/libs/{{item}}'
    state: absent
    force: true
  become: true
  loop:
    - 'libglib-2.0.so.0.6800.4'
    - 'libgio-2.0.so.0.6800.4'
    - 'libgobject-2.0.so.0.6800.4'
    - 'libgmodule-2.0.so.0.6800.4'
